spring:
  application:
    name: analytics

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/analytics
    username: analytics
    password: analytics

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: ${HOSTNAME}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-interval-ms: 30000
      max-poll-records: 100
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
